# Numpy Tutorial

**Array is the data structure that store the same data type element. 
differnce between array and list, list store differnent data type of the element but array store element with same data type** 

In [1]:
import numpy as np               #import numpy lib

# 1D array

In [2]:
myarray=np.array([[1,43,23,67,19]],np.int8)       #use array using numpy

In [3]:
myarray

array([[ 1, 43, 23, 67, 19]], dtype=int8)

In [4]:
myarray[0,3]

np.int8(67)

In [5]:
myarray[0,1]

np.int8(43)

In [6]:
myarray.shape

(1, 5)

In [7]:
myarray.dtype

dtype('int8')

In [8]:
myarray[0,1]=100

In [9]:
myarray

array([[  1, 100,  23,  67,  19]], dtype=int8)

In [10]:
myarray[0,0]

np.int8(1)

In [11]:
myarray

array([[  1, 100,  23,  67,  19]], dtype=int8)

# 2D Array Creation

In [12]:
larr=np.array([[1,2,3,4,2],[5,3,7,4,8],[6,2,3,6,2]])           #create the 3row 5 col array of 2D

In [13]:
larr

array([[1, 2, 3, 4, 2],
       [5, 3, 7, 4, 8],
       [6, 2, 3, 6, 2]])

In [14]:
larr.dtype

dtype('int64')

In [15]:
larr.shape

(3, 5)

In [16]:
larr.reshape(5,3)            #only convert 5 by 3 not stored in larr 

array([[1, 2, 3],
       [4, 2, 5],
       [3, 7, 4],
       [8, 6, 2],
       [3, 6, 2]])

In [17]:
larr.size

15

In [18]:
larr

array([[1, 2, 3, 4, 2],
       [5, 3, 7, 4, 8],
       [6, 2, 3, 6, 2]])

In [19]:
larr.itemsize

8

In [20]:
larr[2,1]

np.int64(2)

In [21]:
larr[2,1]=45

In [22]:
larr

array([[ 1,  2,  3,  4,  2],
       [ 5,  3,  7,  4,  8],
       [ 6, 45,  3,  6,  2]])

# Indexing

In [23]:
arr=np.array([[1,2,3,4,2],[5,3,7,4,8],[6,2,3,6,2]])    

In [24]:
arr

array([[1, 2, 3, 4, 2],
       [5, 3, 7, 4, 8],
       [6, 2, 3, 6, 2]])

In [25]:
arr[:,:]

array([[1, 2, 3, 4, 2],
       [5, 3, 7, 4, 8],
       [6, 2, 3, 6, 2]])

In [26]:
arr[0:2,:]

array([[1, 2, 3, 4, 2],
       [5, 3, 7, 4, 8]])

In [27]:
arr[0:2,0:3]

array([[1, 2, 3],
       [5, 3, 7]])

In [28]:
arr[:,3:]

array([[4, 2],
       [4, 8],
       [6, 2]])

In [29]:
arr[2:,3:]

array([[6, 2]])

In [30]:
#copy function and Broadcasting
arr[:,3:]=100

In [31]:
arr

array([[  1,   2,   3, 100, 100],
       [  5,   3,   7, 100, 100],
       [  6,   2,   3, 100, 100]])

**Copy Function**

In [32]:
arr1=np.array([1,23,4,5,72,44])

In [33]:
arr2=arr1         #here it will be copy arr1 to arr2 but when we perform any change to arr2 then it also perfrom on arr1

In [34]:
arr2

array([ 1, 23,  4,  5, 72, 44])

In [35]:
arr2[3:]=100

In [36]:
arr2

array([  1,  23,   4, 100, 100, 100])

In [37]:
arr1

array([  1,  23,   4, 100, 100, 100])

In [38]:
arr2=arr1.copy()           #here only make arr2 copy of arr1 but there is no any relation between arr2 amd arr1 when performing any operation

In [39]:
arr2

array([  1,  23,   4, 100, 100, 100])

In [40]:
arr2[3:]=200

In [41]:
arr2

array([  1,  23,   4, 200, 200, 200])

In [42]:
arr1

array([  1,  23,   4, 100, 100, 100])

# Intrinsic numpy array creation object (Ones/Zeros)

In [43]:
zeros=np.zeros((3,4))

In [44]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
zeros.dtype

dtype('float64')

In [46]:
range=np.arange(20)       #act like as for loop

In [47]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
range=np.arange(5,14)

In [49]:
range

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [50]:
range1=np.arange(1,21).reshape(4,5)

In [51]:
range1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
lspace=np.linspace(1,13,4)             #act like as loop(start,end,step)

In [53]:
lspace

array([ 1.,  5.,  9., 13.])

In [54]:
ety=np.empty((2,3))             #make empty of 2,3 array

In [55]:
ety

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [4.67289956e-307, 2.67017691e-306, 2.42092166e-322]])

In [56]:
emty_like=np.empty_like(lspace)

In [57]:
emty_like

array([ 1.,  5.,  9., 13.])

In [58]:
ide=np.identity(12)        

In [59]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [60]:
ide.shape

(12, 12)

In [61]:
a=np.arange(99)

In [62]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [63]:
a=a.reshape(3,33)

In [64]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [65]:
a=a.ravel()

In [66]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [67]:
a.shape

(99,)

# Axis

In [68]:
a=[[1,2,3],[4,5,6],[7,8,9]]

In [69]:
import numpy as np

In [70]:
ar=np.array(a)

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
ar.sum(axis=0)

array([12, 15, 18])

In [73]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [74]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [75]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [76]:
ar.ndim

2

In [77]:
ar.nbytes

72

# 1D array Method

In [78]:
oneD=np.array([1,4,2,7,5,3])

In [79]:
oneD.argmax()

np.int64(3)

In [80]:
oneD.argmin()

np.int64(0)

In [81]:
oneD.argsort()

array([0, 2, 5, 1, 4, 3])

In [82]:
oneD.ravel()

array([1, 4, 2, 7, 5, 3])

In [83]:
oneD.reshape(6,1)

array([[1],
       [4],
       [2],
       [7],
       [5],
       [3]])

# 2D Array Method

In [84]:
a=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [85]:
a.argmin()

np.int64(8)

In [86]:
a.argmax()

np.int64(6)

In [87]:
a.argmax(axis=0)

array([2, 1, 1])

In [88]:
a.argmax(axis=1)

array([2, 2, 0])

In [89]:
a.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [90]:
a.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [91]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
ar2=np.array([[3, 4, 3],
       [23, 11, 2],
       [1, 4, 3]])

In [93]:
ar2

array([[ 3,  4,  3],
       [23, 11,  2],
       [ 1,  4,  3]])

In [94]:
ar+ar2

array([[ 4,  6,  6],
       [27, 16,  8],
       [ 8, 12, 12]])

In [95]:
ar*ar2

array([[ 3,  8,  9],
       [92, 55, 12],
       [ 7, 32, 27]])

In [96]:
np.vstack((ar,ar2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  4,  3],
       [23, 11,  2],
       [ 1,  4,  3]])

In [97]:
np.hstack((ar,ar2))

array([[ 1,  2,  3,  3,  4,  3],
       [ 4,  5,  6, 23, 11,  2],
       [ 7,  8,  9,  1,  4,  3]])

In [98]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [99]:
ar.sum()

np.int64(45)

In [100]:
ar.max()

np.int64(9)

In [101]:
ar.min()

np.int64(1)

In [102]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
np.where(ar>6) 

(array([2, 2, 2]), array([0, 1, 2]))

In [104]:
type(np.where(ar>6))

tuple

In [105]:
np.count_nonzero(ar)

9

In [106]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

# Random

In [107]:
ran=np.random.rand(4,3)            #make the 4 by 3 array with assign random value

In [108]:
ran

array([[0.6801484 , 0.62232595, 0.19734091],
       [0.5616836 , 0.36370296, 0.50468093],
       [0.14228089, 0.13440644, 0.13828441],
       [0.01268796, 0.54537332, 0.17402797]])

# Read and Write Text Files

In [109]:
x=np.array([[1,3,2],[5,4,6],[8,9,0]])

#Read File

In [110]:
np.savetxt("D:/Jupyter/text1.txt",x)

#Write File

In [112]:
y=np.loadtxt("D:/Jupyter/text1.txt")
print(y)

[[1. 3. 2.]
 [5. 4. 6.]
 [8. 9. 0.]]


#References for more about numpy-->> Scipy website